apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullname" . }}
  labels: {{ include "labels" . | fromYaml | toJson }}
spec:
  serviceName: {{ include "fullname" . }}
  replicas: 1
  selector:
    matchLabels: {{ include "selectorLabels" . | fromYaml | toJson }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{ toJson . }}
      {{- end }}
      labels: {{ include "selectorLabels" . | fromYaml | toJson }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toJson . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toJson . }}
      {{- end }}
      containers:
      - name: node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - /concordium-node
        - --data-dir=/mnt/data
        - --config-dir=/mnt/data
        - --bootstrap-node=bootstrap.mainnet.concordium.software:8888
        - --rpc-server-addr=0.0.0.0
        - --prometheus-server
        - --prometheus-listen-addr=0.0.0.0
        - --no-dnssec
        ports:
        - name: p2p
          containerPort: 8888
        - name: rpc
          containerPort: 10000
        - name: metrics
          containerPort: 9090
        {{- with .Values.resources }}
        resources: {{ toJson . }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toJson . }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /mnt/data
      {{- if .Values.nodeName }}
      - name: collector
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - /node-collector
        - --collector-url=http://dashboard.mainnet.concordium.software/nodes/post
        - --grpc-host=http://localhost:10000
        - --node-name={{ .Values.nodeName }}
      {{- end }}
      initContainers:
      - name: init-genesis
        image: "{{ .Values.genesisImage.repository }}:{{ .Values.genesisImage.tag }}"
        env:
        - name: DATA_DIR
          value: /mnt/data
        volumeMounts:
        - name: data
          mountPath: /mnt/data
      enableServiceLinks: false
      {{- with .Values.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toJson . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toJson . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toJson . }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ default "standard" .Values.storage.className }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
