version: '3.9'
services:
  node_oob_catchup:
    image: curlimages/curl:latest
    pull_policy: always
    user: root
    environment:
    - OOB_CATCHUP_REFRESH_AGE_SECS
    volumes:
    - data:/mnt/data
    entrypoint:
    - /bin/sh
    - -xc
    - |
      # Compute number of seconds since last modification of '/mnt/data/lock.mdb'.
      # If the file doesn't exist, the "age" defaults to the current Unix time.
      last_ts="$$(stat -c %Y /mnt/data/lock.mdb 2>/dev/null || echo 0)"
      now_ts="$$(date +%s)"
      age_secs="$$((now_ts - last_ts))"

      # Fetch blocks unless age is less than configured limit which defaults to "now" (i.e. never).
      [ "$${age_secs}" -lt "$${OOB_CATCHUP_REFRESH_AGE_SECS-$${now_ts}}" ] ||
        curl -sSf https://catchup.${DOMAIN}/blocks_to_import.mdb -o /mnt/data/blocks.mdb
  node:
    image: ${NODE_IMAGE}
    entrypoint: /concordium-node
    environment:
    - CONCORDIUM_NODE_DATA_DIR=/mnt/data
    - CONCORDIUM_NODE_CONFIG_DIR=/mnt/config
    - CONCORDIUM_NODE_CONSENSUS_IMPORT_BLOCKS_FROM=/mnt/data/blocks.mdb
    - CONCORDIUM_NODE_CONSENSUS_GENESIS_DATA_FILE=/mnt/genesis.dat
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrap.${DOMAIN}:8888
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    - CONCORDIUM_NODE_PROMETHEUS_SERVER=1
    - CONCORDIUM_NODE_PROMETHEUS_LISTEN_ADDRESSS=0.0.0.0
    # We currently cannot define a shorthand variable for 'CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING' specifically,
    # because the application enables tx logging if it's defined with *any* value (including empty).
    # The only way that Docker Compose supports defining the variable on some cases and not others
    # is to pass it directly like this.
    # The node parses the variable through the library 'clap' which improved this behavior in v3.0.0
    # (in 'https://github.com/clap-rs/clap/pull/2664' to be precise),
    # but the node has not yet upgraded past that version.
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING_NAME=${TXLOG_PGDATABASE-concordium_txlog}
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING_HOST=${TXLOG_PGHOST-172.17.0.1}
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING_PORT=${TXLOG_PGPORT-5432}
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING_USERNAME=${TXLOG_PGUSER-postgres}
    - CONCORDIUM_NODE_TRANSACTION_OUTCOME_LOGGING_PASSWORD=${TXLOG_PGPASSWORD-}
    - CONCORDIUM_NODE_LOG_LEVEL_DEBUG
    # Defer container start until the init containers have completed successfully.
    # Note that no logs are emitted on stdout until all containers have started.
    # Also, this syntax requires Docker Compose v. 1.29+.
    depends_on:
      node_oob_catchup:
        condition: service_completed_successfully
    networks:
    - concordium
    ports:
    - "8888:8888"   # P2P
    - "10000:10000" # gRPC
    - "9090:9090"   # Prometheus (metrics)
    volumes:
    - ${GENESIS_DATA_FILE}:/mnt/genesis.dat
    - data:/mnt/data
    - config:/mnt/config
    build:
      context: .
      args:
        tag: ${NODE_TAG}
  node-collector:
    image: ${NODE_IMAGE}
    entrypoint: /node-collector
    environment:
    - CONCORDIUM_NODE_COLLECTOR_URL=https://dashboard.${DOMAIN}/nodes/post
    - CONCORDIUM_NODE_COLLECTOR_GRPC_HOST=http://node:10000
    - CONCORDIUM_NODE_COLLECTOR_NODE_NAME=${NODE_NAME}
    - CONCORDIUM_NODE_COLLECTOR_ARTIFICIAL_START_DELAY=120000 # 2m
    depends_on:
    - node
    networks:
    - concordium
    restart: unless-stopped  # service may time out before the node is operational
                             # (shouldn't use 'on-failure' as that will make the container auto start on boot)
    stop_signal: SIGKILL     # application doesn't react to SIGINT nor SIGTERM
  node-dashboard-grpc-proxy:
    profiles: [node-dashboard]
    image: envoyproxy/envoy:v1.18-latest
    pull_policy: always
    entrypoint: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml
    depends_on:
    - node
    networks:
    - concordium
    ports:
    - "9901:9901" # admin
    - "9999:9999" # proxy
    volumes:
    - ./node-dashboard/envoy.yaml:/etc/envoy/envoy.yaml:ro
  node-dashboard:
    profiles: [node-dashboard]
    image: ${NODE_DASHBOARD_IMAGE}
    depends_on:
    - node-dashboard-grpc-proxy
    networks:
    - concordium
    ports:
    - "8099:80" # web
    build:
      context: ./node-dashboard
      args:
        tag: main
volumes:
  data:
  config:
networks:
  concordium:
