version: '3.9'
services:
  node_oob_catchup:
    image: curlimages/curl:latest
    user: 1000
    volumes:
    - data:/mnt/data
    entrypoint:
    - /bin/sh
    - -c
    - |
      [ -f /mnt/data/blocks.mdb ] ||
        curl -sSf https://catchup.${DOMAIN}/blocks_to_import.mdb -o /mnt/data/blocks.mdb
  node:
    image: ${NODE_IMAGE}
    user: 1000
    entrypoint: /concordium-node
    environment:
    - CONCORDIUM_NODE_DATA_DIR=/mnt/data
    - CONCORDIUM_NODE_CONFIG_DIR=/mnt/config
    - CONCORDIUM_NODE_CONSENSUS_IMPORT_BLOCKS_FROM=/mnt/data/blocks.mdb
    - CONCORDIUM_NODE_CONSENSUS_GENESIS_DATA_FILE=/mnt/genesis.dat
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrap.${DOMAIN}:8888
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    - CONCORDIUM_NODE_PROMETHEUS_SERVER=1
    - CONCORDIUM_NODE_PROMETHEUS_LISTEN_ADDRESSS=0.0.0.0
    # Defer container start until the init containers have completed successfully.
    # Note that no logs are emitted on stdout until all containers have started.
    # Also, this syntax requires Docker Compose v. 1.29+.
    depends_on:
      node_oob_catchup:
        condition: service_completed_successfully
    networks:
    - concordium
    ports:
    - "8888:8888"   # P2P
    - "10000:10000" # gRPC
    - "9090:9090"   # Prometheus (metrics)
    volumes:
    - ${GENESIS_DATA_FILE}:/mnt/genesis.dat
    - data:/mnt/data
    - config:/mnt/config
    build:
      context: .
      args:
        tag: ${NODE_TAG}
  node-collector:
    image: ${NODE_IMAGE}
    user: 1000
    entrypoint: /node-collector
    environment:
    - CONCORDIUM_NODE_COLLECTOR_URL=https://dashboard.${DOMAIN}/nodes/post
    - CONCORDIUM_NODE_COLLECTOR_GRPC_HOST=http://node:10000
    - CONCORDIUM_NODE_COLLECTOR_NODE_NAME=${NODE_NAME}
    depends_on:
    - node
    networks:
    - concordium
  node-dashboard-grpc-proxy:
    image: envoyproxy/envoy:v1.18-latest
    user: 1000
    entrypoint: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml
    depends_on:
    - node
    networks:
    - concordium
    ports:
    - "9901:9901" # admin
    - "9999:9999" # proxy
    volumes:
    - ./node-dashboard/envoy.yaml:/etc/envoy/envoy.yaml:ro
  node-dashboard:
    image: ${NODE_DASHBOARD_IMAGE}
    user: 1000
    depends_on:
    - node-dashboard-grpc-proxy
    networks:
    - concordium
    ports:
    - "8099:80" # web
    build:
      context: ./node-dashboard
      args:
        tag: main
volumes:
  data:
  config:
networks:
  concordium:
