version: '3'
services:
  genesis:
    container_name: node-init-genesis
    image: ${GENESIS_IMAGE}
    environment:
    - DATA_DIR=/data
    network_mode: none
    volumes:
    - data:/data
    build:
      context: genesis
      args:
        genesis_file: ${GENESIS_VERSION}.dat
  node:
    container_name: node
    image: ${NODE_IMAGE}
    command: >-
      /concordium-node
        --data-dir=/data
        --config-dir=/config
        --bootstrap-node=bootstrap.mainnet.concordium.software:8888
        --rpc-server-addr=0.0.0.0
        --prometheus-server
        --prometheus-listen-addr=0.0.0.0
        --no-dnssec
    depends_on:
    - genesis
    networks:
    - concordium
    ports:
    - 8888:8888
    - 10000:10000
    volumes:
    - data:/data
    - config:/config
    build:
      context: .
      args:
        tag: ${NODE_TAG}
  node-collector:
    container_name: node-collector
    image: ${NODE_IMAGE}
    command: >-
      /node-collector
        --collector-url=http://dashboard.mainnet.concordium.software/nodes/post
        --grpc-host=http://node:10000
        --node-name=${NODE_NAME}
    depends_on:
    - node
    networks:
    - concordium
  node-dashboard-grpc-proxy:
    container_name: node-dashboard-grpc-proxy
    image: envoyproxy/envoy:v1.18-latest
    command: /usr/local/bin/envoy --config-path /etc/envoy/envoy.yaml
    depends_on:
    - node
    networks:
    - concordium
    ports:
    - "9901:9901" # admin
    - "9999:9999" # proxy
    volumes:
    - ./node-dashboard/envoy.yaml:/etc/envoy/envoy.yaml:ro
  node-dashboard:
    container_name: node-dashboard
    image: ${NODE_DASHBOARD_IMAGE}
    depends_on:
    - node-dashboard-grpc-proxy
    networks:
    - concordium
    ports:
    - "8099:8099"
    build:
      context: ./node-dashboard
      args:
        tag: main
volumes:
  data:
  config:
networks:
  concordium:
