# Default values for concordium-node.

# domain is the domain of the network and is used to locate the bootstrapper and dashboard backend for the collector.
# If empty, then the value is inferred from the network field (below) as follows:
# - If network is "mainnet", then domain is "mainnet.concordium.software".
# - Otherwise, domain is "<network>.concordium.com".
domain: ""

# network is the name of the network to join.
# The chart expects to find a field with the name of the network in the configmap 'genesis'.
# The value of network is used to infer the domain field in case it's empty, as described above.
network: testnet

node:
  # name is the name of the node to be presented on the public dashboard.
  # Leaving empty will disable the collector container entirely.
  name: ""
  # image is the name of the image used for the 'node' container.
  image: "bisgardo/concordium-node:3.0.2-0_1"
  # collectorImage is the name of the image used for the 'collector' container.
  # If empty, this defaults to the node image.
  collectorImage: ""

# service configures the service type and the ports of the individual endpoints exposed by the service.
service:
  type: NodePort
  ports:
    p2p: 8888
    metrics: 9090
    rpc: 10000

# storage configures the class and size of the persistent volume in which the LMDB database is stored.
storage:
  className: standard
  size: 100Gi

# The fields below are kept from the scaffolding initialized by Helm to do detailed configuration of the deployment.
# See their use in 'templates/statefulset.yaml' and lookup the docs of the relevant fields in the official API docs
# (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/).

nameOverride: ""
fullnameOverride: ""
restartPolicy: Always
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

# test configures test parameters.
test:
  # concordiumClientVersion is the version used to query the node in tests.
  concordiumClientVersion: 3.0.4-0
