# Default values for concordium-node.

# nodeName is the name of the node to be presented on the public dashboard.
# Leave empty to disable the collector container entirely.
nodeName: test

# image is the image repository and tag to used for the 'node' and 'collector' containers.
image:
  repository: bisgardo/concordium-node
  tag: "1.0.1-0_1"

# genesisImage is the image repository and tag to used for the 'init-genesis` container.
genesisImage:
  repository: bisgardo/concordium-node-genesis
  tag: "mainnet-1"

# service configures the service type and the ports of the individual endpoints exposed by the service.
service:
  type: NodePort
  ports:
    p2p: 8888
    metrics: 9090
    rpc: 10000

# storage configures the class and size of the persistent volume that the database is stored in.
storage:
  className: standard
  size: 10Gi

# The fields below are kept from the scaffolding initialized by Helm to do detailed configuration of the deployment.
# See their use in 'templates/statefulset.yaml' and lookup the docs of the relevant fields in the official API docs
# (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/).

restartPolicy: Always
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
