# Default values for concordium-node.

nodeName: test

image:
  repository: bisgardo/concordium-node
  tag: "1.0.1-0_0"

genesisImage:
  repository: bisgardo/concordium-node-genesis
  tag: "mainnet-1_0"

service:
  type: NodePort
  ports:
    p2p: 8888
    metrics: 9090
    rpc: 10000

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
