name: Build and push

on:
  workflow_dispatch: # manual trigger
    inputs:
      build_version:
        description: 'String used as suffix to the image tags to ensure uniqueness.'
        required: true
      node_tag:
        description: 'Tag from the concordium-node repository to build from.'
        required: true
      genesis_tag:
        description: 'Genesis data file name in the "genesis" directory.'
        required: true
        default: 'mainnet-1'

env:
  node_image_repo: 'bisgardo/concordium-node'
  genesis_image_repo: 'bisgardo/concordium-node-genesis'
  node_tag: '${{ github.event.inputs.node_tag }}'
  genesis_version: '${{ github.event.inputs.genesis_version }}'
  build_version: '${{ github.event.inputs.build_version }}'
  
jobs:
  build-push:
    env:
      node_image: '${{ env.node_image_repo }}:${{ env.node_tag }}_${{ env.build_version }}'
      genesis_image: '${{ env.genesis_image_repo }}:${{ env.genesis_version }}_${{ env.build_version }}'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build node and genesis images
      run: >-
        NODE_NAME=
        NODE_TAG="${{ env.node_tag }}"
        GENESIS_VERSION="${{ env.genesis_version }}"
        NODE_IMAGE="${{ env.node_image }}"
        GENESIS_IMAGE="${{ env.genesis_image }}"
        docker-compose build
    - name: Push node and genesis images
      run: |
        docker login --username bisgardo --password-stdin <<< "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
        docker push "${{ env.node_image }}"
        docker push "${{ env.genesis_image }}"
