name: Build and push

on: # yamllint disable-line rule:truthy
  workflow_dispatch: # manual trigger
    inputs:
      node_tag:
        description: 'Node tag'
        required: true
      genesis_version:
        description: 'Genesis version'
        required: true
        default: 'mainnet-1'
      node_image_tag:
        description: 'Node image tag'
        required: true
      genesis_image_tag:
        description: 'Genesis image tag'
        required: true
        default: 'mainnet-1'
      node_dashboard_image_tag:
        description: 'Node Dashboard image tag'
        required: true
        default: 'latest'

env:
  user: bisgardo
  node_image_repo: 'bisgardo/concordium-node'
  genesis_image_repo: 'bisgardo/concordium-node-genesis'
  node_dashboard_image_repo: 'bisgardo/concordium-node-dashboard'
  node_tag: '${{ github.event.inputs.node_tag }}'
  genesis_version: '${{ github.event.inputs.genesis_version }}'
  node_image_tag: '${{ github.event.inputs.node_image_tag }}'
  genesis_image_tag: '${{ github.event.inputs.genesis_image_tag }}'
  node_dashboard_image_tag: '${{ github.event.inputs.node_dashboard_image_tag }}'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: docker login --username "${{ env.user }}" --password-stdin <<< "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
    - name: Build and push node and genesis images
      run: |
        export NODE_TAG="${{ env.node_tag }}"
        export GENESIS_VERSION="${{ env.genesis_version }}"
        export NODE_IMAGE="${{ env.node_image_repo }}:${{ env.node_image_tag }}"
        export GENESIS_IMAGE="${{ env.genesis_image_repo }}:${{ env.genesis_image_tag }}"
        export NODE_DASHBOARD_IMAGE=${{ env.node_dashboard_image_repo }}:${{ env.node_dashboard_image_tag }}
        NODE_NAME= docker-compose build && docker-compose push
